### ISSUE TITLE
Parsing should never wrap

### ISSUE THREAD

**Issue by jasperpotts** [hashgraph/pbj#104]
### Description

When parsing data the input buffer can not be assumed to be owned by parser so wrapped bytes can never pass though parsing.

### Steps to reproduce

Parse a protobuf object with field of type bytes from a byte[] backed BufferedData. Then change the input byte[] after and the byte value in parsed object will change.

### Hedera network

other

### Version

0

### Operating system

None

**Comment by artemananiev** [comment]
A couple notes here:

1. This issue is applicable to multiple types: `Bytes`, `BufferedData`, and probably more

2. For performance reasons, methods like `BufferedData.wrap(byte[])` are designed to use the provided byte array, so any changes to the array are reflected in the `Bytes` object. This is done for a good reason and should not be changed as a part of this task. This task is to make sure PBJ generated classes don't leak the underlying byte arrays

**Comment by anthony-swirldslabs** [comment]
Will also need to remove usages of toReadableSequentialData() from hedera-services repo before closing the story.
