### ISSUE TITLE
Consider replacing `assert` with `throw`

### ISSUE THREAD

**Issue by anthony-swirldslabs** [hashgraph/pbj#150]
### Description

PBJ code has a number of `assert` checks in it code-base. Both the generated codecs as well as the runtime use `assert` for some verifications.

Experiments with fuzz testing (being implemented at https://github.com/hashgraph/pbj/issues/68 ) show that certain payload modifications result in those asserts being triggered. This means that the assumptions expressed in the `assert` statements may not hold true when the payload is malformed, which may result in an incorrect behavior of the codecs when deserializing objects.

The proposal is to replace some or all the `assert` statements with proper `if`/`throw` clauses to actually fail the codec when its assumptions aren't true.

The only downside worth considering is a slight performance degradation in production where asserts are normally disabled, and therefore those validation checks don't run currently. Once they're converted to if/throw, the validations will run and hence consume a bit of resources.

### Steps to reproduce

Run the fuzz tests that are being built under https://github.com/hashgraph/pbj/issues/68 , and modify the

https://github.com/hashgraph/pbj/blob/main/pbj-integration-tests/src/main/java/com/hedera/pbj/integration/fuzz/SingleFuzzTest.java

to NOT catch the java.lang.AssertionError. A few fuzz tests will start failing by throwing this error.

### Hedera network

other

### Version

v

### Operating system

None

**Comment by jasperpotts** [comment]
This was very intentional. The aim was to use asserts to protect against things breaking when the code is changed or refactored. It allows you to codify assumptions and understandings into the code. They are enabled when tests run and will give more meaningful errors. It should be that all cases will throw an exception and fail in some way in production, like null pointer or buffer overflow etc. So throwing another exception is expensive and doesn't make the code safer. It would just give a more helpful error message. As PBJ performance is critical, it is used very heavily throughout the consensus node in performance critical threads. We have chosen performance over helpful errors in production.

**Comment by anthony-swirldslabs** [comment]
This makes sense. I will look into running the fuzz tests with assertions off, so as to catch the actual failures as they happen in prod, rather than deal with the AssertionError. So we won't fix this particular issue.
