### ISSUE TITLE
Horrible performance of ProtoWriterTools#writeBytes()

### ISSUE THREAD

**Issue by jasperpotts** [hashgraph/pbj#191]
### Description

The `com.hedera.pbj.runtime.ProtoWriterTools#writeBytes(...)` method does not have a fast path when writing to a `WritableStreamingData`. It does not have fast path implementations of writeBytes methods and uses the dumb default implementations from `WritableSequentialData` like:
```
    default void writeBytes(@NonNull final byte[] src, final int offset, final int length) {
        if (length < 0) {
            throw new IllegalArgumentException("length must be >= 0");
        }

        for (int i = offset; i < (offset+length); i++) {
            writeByte(src[i]);
        }
    }
```

We need fast paths for all cases and maybe should even get rid of the dumb implementations so they are never used by accident! The fast paths need to write any bytes content for example `RandomAccessData` to the stream without copies and in a single write call.

### Steps to reproduce

Benchmark WritableSequentialData#writeBytes() with multi KB byte arrays writing to a file and performance is horrible. 40 per second with 16KB on M1 Mac Book :-( 
Also benchmark writing a PBJ object to a file with Bytes field of multi KB which calls into above.

**Comment by anthony-swirldslabs** [comment]
Jasper started a PR at https://github.com/hashgraph/pbj/pull/193 which I'll pick up.

I will also need to check if other methods that write byte[], ByteBuffer and similar might need an optimized override.

**Comment by anthony-swirldslabs** [comment]
After checking the read/get/writeBytes methods, here's the summary of identified issues by interfaces:

### WritableSequentialData:
1. CharBufferToWritableSequentialData is slow all around
2. WritableStreamingData.writeBytes(ByteBuffer) is FAST for hasArray, otherwise SLOW
3. WritableStreamingData.writeBytes(BufferedData) is SLOW
4. writeBytes(InputStream src) had a moderate 8K buffer by default, but is the most optimal in ByteArrayBufferedData
5. *BufferedData.writeBytes(RandomAccessData) is only fast for Bytes, but slow for any other RandomAccessData. Should be okay, unless it's explicitly called for a BufferedData instead of the native writeBytes(BufferedData)

### ReadableSequentialData:
1. CharBufferToWritableSequentialData is slow all around
2. readBytes(ByteBuffer) often supports only hasArray (or isDirect) on the fast path
3. ReadableStreamingData.readBytes(BufferedData) is FAST for ByteArrayBufferedData, SLOW for CharBufferToWritableSequentialData, and moderately buffered for others

### RandomAccessData:
1. contains/matchesPrefix(RandomAccessData)
2. contains/matchesPrefix(byte[]) for DirectBufferedData and vanilla BufferedData (!hasArray && !isDirect)
