### ISSUE TITLE
(EXISTENTIAL) Reference fields generated with `@NonNull` are assumed non-null but not required to be

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/pbj#211]
### Description

Consider the following test:
```
    @Test
    void gameOver() {
        final var protoBytes = new ProtoBytes(null);
        ProtoBytes.PROTOBUF.toBytes(protoBytes);
    }
```
The _second_ line throws an NPE:
```
java.lang.NullPointerException: Cannot invoke "com.hedera.pbj.runtime.io.buffer.RandomAccessData.length()" because "value" is null
	at com.hedera.pbj.runtime.ProtoWriterTools.writeBytesNoChecks(ProtoWriterTools.java:327)
	at com.hedera.pbj.runtime.ProtoWriterTools.writeBytes(ProtoWriterTools.java:294)
	at com.hedera.hapi.node.state.primitives.codec.ProtoBytesProtoCodec.write(ProtoBytesProtoCodec.java:71)
```

As PBJ is used in Services, this means:
 - A transaction handled at consensus could silently put a `ProtoBytes` with null value into a mutable state; which would,
 - Asynchronously kill the state-hashing threads after the state is fast-copied; and,
 - Shut down the entire network.

### Steps to reproduce

As above.

### Hedera network

other

### Version

`develop`

### Operating system

None

**Comment by jasperpotts** [comment]
We have two options here:

**Comment by anthony-swirldslabs** [comment]
Converting null to a default value would require adding an explicit constructor to the generated record, which seems to add a lot of boilerplate code. While our Builder implementation substitute null Bytes with Bytes.EMPTY, the Protobuf Java spec says "Note that no Java protocol buffer methods accept or return nulls unless otherwise specified": https://protobuf.dev/reference/java/java-generated/ . And null is only mentioned in the context of enums, and only as a return value.

So it seems reasonable to update the record validator constructor to throw an NPE when the supplied Bytes is null.

Protobuf also defaults strings to empty strings, so it seems reasonable to treat them in a way similar to how we treat Bytes.
