### ISSUE TITLE
ReadableStreamingData should implement bulk read methods

### ISSUE THREAD

**Issue by jasperpotts** [hashgraph/pbj#27]
### Problem

ReadableStreamingData should implement efficient versions of the InputStream bulk read methods.
```
    public long readBytes(@NonNull byte[] dst) {
    public long readBytes(@NonNull final byte[] dst, final int offset, final int maxLength) {
```
As the default just call read() in a loop which is not idea. Most InputStream sub classes like FileInputStream have efficient implementations

### Solution

Something like this maybe
```
    /** {@inheritDoc} */
    @Override
    public long readBytes(@NonNull byte[] dst) {
        return readBytes(dst, 0, dst.length);
    }

    /** {@inheritDoc} */
    @SuppressWarnings("DuplicatedCode")
    public long readBytes(@NonNull final byte[] dst, final int offset, final int maxLength) {
        if (maxLength < 0) {
            throw new IllegalArgumentException("Negative maxLength not allowed");
        }
        // return 0 if there is no data remaining to be read
        if (!hasRemaining()) return 0;

        int maxReadable = Math.min((int)Math.min(Integer.MAX_VALUE,remaining()), maxLength);
        try {
            int readBytes =  in.read(dst,offset,maxReadable);
            // our spec differs from InputStream that we return 0 when no bytes available to read because we reached
            // end of the file.
            if (readBytes == -1) {
                eof == true;
                return 0;
            }
            return readBytes;
        } catch (IOException e) {
            throw new DataAccessException(e);
        }
    }
```

**Comment by artemananiev** [comment]
It appeared to be slightly more complicated than the proposed code snippet above. The issue is with `eof`. The streaming object is expected to reach EOF even if it was able to read some bytes. That it, checking the result of `in.read()` against -1 is not enough. There is test for that: it creates a byte array input stream over an array of 10 elements, then tries to read 12 bytes from it. 10 bytes are expected to be read (this is fine), but in addition to that, hasRemaining() is expected to be false. With the proposed implementation above it will be true: `eof` is still false, and position (10) is less than limit (which is usually Long.MAX_VALUE for streaming data, but in this particular test is set to 12).
